export { WelcomeEmail } from './patient/WelcomeEmail'
export { GenericWelcomeEmail } from './GenericWelcomeEmail'
export { AppointmentBookedEmail } from './patient/AppointmentBooked'
export { AppointmentCancelledEmail } from './patient/AppointmentCancelled'
export { PrescriptionReadyEmail } from './patient/PrescriptionReady'
export { PractitionerApplicationReceivedEmail } from './practitioner/ApplicationReceived'
export { PractitionerAccountApprovedEmail } from './practitioner/AccountApproved'
export { PractitionerProfileSetupInvitationEmail } from './practitioner/ProfileSetupInvitation'
export { PractitionerReapprovalReminderEmail } from './practitioner/ReapprovalReminder'
export { ClinicApplicationReceivedEmail } from './clinic/ApplicationReceived'
export { ClinicAccountApprovedEmail } from './clinic/AccountApproved'
export { ClinicDocumentRenewalReminderEmail } from './clinic/DocumentRenewalReminder'
export { AdminNewPractitionerEmail } from './admin/NewPractitionerRegistration'
export { AdminNewClinicEmail } from './admin/NewClinicRegistration'
export { AdminDocumentExpiryAlertEmail } from './admin/DocumentExpiryAlert'
export { AdminTeamMemberCredentialsEmail } from './admin/TeamMemberCredentials'


